name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "api-gateway/**"
      - ".github/workflows/deploy-api-gateway.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: |
            muhammedanees786/api-gateway:latest
            muhammedanees786/api-gateway:${{ github.sha }}

      - name: Deploy to K3s
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2_key \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
            "sudo kubectl set image deployment/api-gateway \
            api-gateway=muhammedanees786/api-gateway:${{ github.sha }} \
            -n secondproject"

      - name: Wait for rollout
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2_key \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
            "sudo kubectl rollout status deployment/api-gateway \
            -n secondproject --timeout=180s"